local data_util = require("data_util")

-- Smelt-Crafting category doesn't particularly fit the theme of SE yet.
data_util.delete_recipe("kr-s-c-copper-cable")
data_util.delete_recipe("kr-s-c-copper-cable-enriched")
data_util.delete_recipe("kr-s-c-iron-stick")
data_util.delete_recipe("kr-s-c-iron-stick-enriched")
data_util.delete_recipe("kr-s-c-iron-beam")
data_util.delete_recipe("kr-s-c-iron-beam-enriched")
data_util.delete_recipe("kr-s-c-steel-beam")
data_util.delete_recipe("kr-s-c-imersium-beam")
data_util.delete_recipe("kr-s-c-iron-gear-wheel")
data_util.delete_recipe("kr-s-c-iron-gear-wheel-enriched")
data_util.delete_recipe("kr-s-c-steel-gear-wheel")
data_util.delete_recipe("kr-s-c-imersium-gear-wheel")
data_util.delete_recipe("kr-s-c-electronic-components")