local data_util = require("data_util")

data:extend{
  {
    type = "sprite",
    name = data_util.mod_prefix .. "pin-add",
    filename = "__space-exploration-graphics__/graphics/icons/signal/pin-add.png",
    priority = "extra-high",
    width = 64,
    height = 64,
    shift = {0,0}
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "pin-list",
    filename = "__space-exploration-graphics__/graphics/icons/signal/pin-list.png",
    priority = "extra-high",
    width = 64,
    height = 64,
    shift = {0,0}
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "danger-parts",
    filename = "__space-exploration-graphics-5__/graphics/icons/danger-parts.png",
    priority = "extra-high",
    width = 64,
    height = 64,
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "warning-parts",
    filename = "__space-exploration-graphics-5__/graphics/icons/warning-parts.png",
    priority = "extra-high",
    width = 64,
    height = 64,
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "danger-charge",
    filename = "__space-exploration-graphics-5__/graphics/icons/danger-charge.png",
    priority = "extra-high",
    width = 64,
    height = 64,
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "warning-charge",
    filename = "__space-exploration-graphics-5__/graphics/icons/warning-charge.png",
    priority = "extra-high",
    width = 64,
    height = 64,
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "search-black",
    filename = "__space-exploration-graphics__/graphics/icons/search-black.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    width = 64,
    height = 64,
    shift = {0,0}
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "search-white",
    filename = "__space-exploration-graphics__/graphics/icons/search-white.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    width = 64,
    height = 64,
    shift = {0,0}
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "search-close-black",
    filename = "__space-exploration-graphics__/graphics/icons/search-close-black.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    width = 64,
    height = 64,
    shift = {0,0}
  },
  {
    type = "sprite",
    name = data_util.mod_prefix .. "search-close-white",
    filename = "__space-exploration-graphics__/graphics/icons/search-close-white.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    width = 64,
    height = 64,
    shift = {0,0}
  },
  {
    type = "sprite",
    name = "se-lifesupport-icon",
    filename = "__space-exploration-graphics__/graphics/icons/lifesupport-icon-transparent.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-lifesupport-icon-inverted",
    filename = "__space-exploration-graphics__/graphics/icons/lifesupport-icon-transparent-inverted.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-breadcrumb-left-dark",
    filename = "__space-exploration-graphics__/graphics/icons/breadcrumb-left-dark.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-breadcrumb-right-dark",
    filename = "__space-exploration-graphics__/graphics/icons/breadcrumb-right-dark.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-arrow-left-white",
    filename = "__space-exploration-graphics__/graphics/icons/arrow-left-white.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-arrow-left-black",
    filename = "__space-exploration-graphics__/graphics/icons/arrow-left-black.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-arrow-right-white",
    filename = "__space-exploration-graphics__/graphics/icons/arrow-right-white.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-arrow-right-black",
    filename = "__space-exploration-graphics__/graphics/icons/arrow-right-black.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-pin-add-white",
    filename = "__space-exploration-graphics__/graphics/icons/pin-add-white.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-pin-add-black",
    filename = "__space-exploration-graphics__/graphics/icons/pin-add-black.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-pin-list-white",
    filename = "__space-exploration-graphics__/graphics/icons/pin-list-white.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-pin-list-black",
    filename = "__space-exploration-graphics__/graphics/icons/pin-list-black.png",
    priority = "extra-high",
    flags = {"gui-icon"},
    size = 64
  },
  {
    type = "sprite",
    name = "se-cog-white",
    filename = "__space-exploration-graphics__/graphics/icons/cog-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-cog-black",
    filename = "__space-exploration-graphics__/graphics/icons/cog-black.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-show-white",
    filename = "__space-exploration-graphics__/graphics/icons/show-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-show-black",
    filename = "__space-exploration-graphics__/graphics/icons/show-black.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-flag-settings-white",
    filename = "__space-exploration-graphics__/graphics/icons/flag-settings-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-flag-settings-black",
    filename = "__space-exploration-graphics__/graphics/icons/flag-settings-black.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-flag-white",
    filename = "__space-exploration-graphics__/graphics/icons/flag-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-flag-black",
    filename = "__space-exploration-graphics__/graphics/icons/flag-black.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-cut",
    filename = "__base__/graphics/icons/shortcut-toolbar/mip/cut-x32.png",
    size = 32,
    mipmap_count = 2,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-biter-white",
    filename = "__space-exploration-graphics__/graphics/icons/biter-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-biter-black",
    filename = "__space-exploration-graphics__/graphics/icons/biter-black.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-scan",
    filename = "__space-exploration-graphics__/graphics/icons/scan-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-stop-white",
    filename = "__space-exploration-graphics__/graphics/icons/stop-white.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-stop-black",
    filename = "__space-exploration-graphics__/graphics/icons/stop-black.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  },
  {
    type = "sprite",
    name = "se-landfill-scaffold",
    filename = "__space-exploration-graphics__/graphics/icons/landfill-scaffold-hybrid.png",
    size = 64,
    scale = 0.5,
    flags = { "gui-icon" },
  }
}
