-- Add Raw Rare Metals to meteor shower meteors
table.insert(data.raw["simple-entity"]["se-static-meteor-01"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-02"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-03"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-04"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-05"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-06"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-07"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-08"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-09"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-10"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-11"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-12"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-13"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-14"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-15"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})
table.insert(data.raw["simple-entity"]["se-static-meteor-16"].minable.results, {name = "raw-rare-metals", amount_min = 0, amount_max = 30})